
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/Dockerfile to edit this template

version: '3.8'

services:
  usuarios-servicio:
    build:
      context: ./usuarios-servicio
    ports:
      - "8083:8080"
    networks:
      - ms-network

  asignaturas-servicio:
    build:
      context: ./asignaturas-servicio
    ports:
      - "8081:8080"
    networks:
      - ms-network

  matriculas-servicio:
    build:
      context: ./matriculas-servicio
    ports:
      - "8082:8080"
    networks:
      - ms-network

networks:
  ms-network:
    driver: bridge